source 'git@git.vipaylife.com:vipay/Chaos-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

platform :ios, '9.0'

target 'HDServiceKit_Example' do

  pod 'HDServiceKit', :path => '../'

  target 'HDServiceKit_Tests' do
    inherit! :search_paths


  end
end
