source 'git@git.vipaylife.com:vipay/Chaos-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '9.0'

target 'HDServiceKit_Example' do
  pod 'HDServiceKit', :path => '../'

  target 'HDServiceKit_Tests' do
    inherit! :search_paths


  end
end
