source 'ssh://git@code.kh-super.net:7999/mob/chaos-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

platform :ios, '9.0'

target 'HDServiceKit_Example' do

  pod 'HDServiceKit', :path => '../'
  pod 'HDKitCore/HDMediator'

  target 'HDServiceKit_Tests' do
    inherit! :search_paths


  end
end
